server:
  port: ${dev.view.server.port}
spring:
  security:
    user:
      name: ${dev.view.security.user.name}                               # security默认用户名
      password: ${dev.view.security.user.password}                       # security默认密码
  # 数据库配置
  datasource:
    username: ${dev.view.datasource.username}                            # mysql数据库账号
    password: ${dev.view.datasource.password}                            # mysql数据库密码
knife4j:
  basic:
    enable: false
    username: ${dev.view.knife4j.username}                               # knife4j默认账号
    password: ${dev.view.knife4j.password}                               # knife4j默认密码