server:
  port: ${test.view.server.port}
spring:
  security:
    user:
      name: ${test.view.security.user.name}                               # security默认用户名
      password: ${test.view.security.user.password}                       # security默认密码
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                           # mysql数据库连接驱动
    url: ${dev.view.datasource.url}                                       # mysql数据链接
    username: ${dev.view.datasource.username}                             # mysql数据库账号
    password: ${dev.view.datasource.password}                             # mysql数据库密码
  data:
    redis:
      host: ${dev.view.redis.host}                                        #redis 链接
      port: ${dev.view.redis.port}                                        #redis 端口
      password: ${dev.view.redis.password}                                #redis 密码
      database: 0                                                         #redis 数据库
knife4j:
  basic:
    enable: false
    username: ${test.view.knife4j.username}                               # knife4j默认账号
    password: ${test.view.knife4j.password}                               # knife4j默认密码